//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.11.1.0 (NJsonSchema v10.4.3.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Net.Http;
using System.Threading.Tasks;
using System.Threading;

namespace Repaybl.Swag
{
    public class BaseClient
    {
        public string BaseUrl { get; set; } = "http://localhost:46606/";
        public static string BearerToken { get; private set; }
        public static void SetBearerToken(string token)
        {
            BearerToken = token;
        }
        // Called by implementing swagger client classes
        protected Task<HttpRequestMessage> CreateHttpRequestMessageAsync(CancellationToken cancellationToken)
        {
            var msg = new HttpRequestMessage();
            if (!string.IsNullOrEmpty(BearerToken))
                msg.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", BearerToken);
            return Task.FromResult(msg);
        }
    }
}